services:
  db:
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data # Volume separado para Dev
      - ./db-init:/docker-entrypoint-initdb.d/

  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app # Hot-reload do Python
      - media_volume_dev:/app/media
    environment:
      - DEBUG=True
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}

  frontend:
    command: quasar dev -m pwa --port 9000 --hostname 0.0.0.0
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8080/api/v1 # Porta 8080 para Dev

  nginx:
    ports:
      - "8080:80" # Dev roda na porta 8080
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf # Config com WebSocket
      - media_volume_dev:/var/www/media:ro

volumes:
  postgres_data_dev:
  media_volume_dev: